name: Append ~ to Samples folder

on:
  push:
    branches:
      - main

jobs:
  rename-samples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Rename Samples to Samples~
        run: |
          if [ -d "UnityProject/Saneject/Assets/Plugins/Saneject/Samples" ]; then
            mv "UnityProject/Saneject/Assets/Plugins/Saneject/Samples" "UnityProject/Saneject/Assets/Plugins/Saneject/Samples~"
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: rename Samples to Samples~ for UPM" || echo "No changes"
          git push