name: CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unity: [2022.3.12f1, 6000.0.23f1]
    steps:
      - uses: actions/checkout@v4

      - name: EditMode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unity }}
          testMode: editmode
          projectPath: UnityProject/Saneject
          customParameters: -nographics -quit
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: "EditMode (${{ matrix.unity }})"
